openapi: 3.0.3
info:
  title: Asset Discovery
  description: RESTful API for managing seeds, seed groups used in the asset discovery process.
  version: "1.0"
  contact:
    name: Synack Engineering
    email: engineering@synack.com
tags:
  - name: Seeds
    description: Collections of seeds associated with a listing.
  - name: Tags
    description: Tags applied to seeds and seed groups.
servers:
  - url: https://client.synack.com/api/asset-discovery
    description: Commercial
  - url: https://client.synack.us/api/asset-discovery
    description: FedRAMP (Medium)
paths:
  /v1/organizations/{organizationUid}/seed-groups:
    get:
      operationId: getSeedGroups
      tags:
        - Seeds
      description: >
        Retrieve and filter seed groups.
      x-mint:
        metadata:
          title: Get Seed Groups
      security:
        - OAuth2:
            - assetdiscovery_or
            - assetdiscovery_gr
            - assetdiscovery_lr
    post:
      operationId: postSeedGroup
      tags:
        - Seeds
      description: >
        Creates a new seed group and seeds if valid.
      x-mint:
        metadata:
          title: Create Seed Group
      security:
        - OAuth2:
            - assetdiscovery_ow
            - asset_client_lw

  /v1/organizations/{organizationUid}/seed-groups/{seedGroupUid}:
    get:
      operationId: getSeedGroup
      tags:
        - Seeds
      description: >
        Retrieves a single seed group.
      x-mint:
        metadata:
          title: Get Seed Group
      security:
        - OAuth2:
            - assetdiscovery_or
    patch:
      operationId: patchSeedGroup
      tags:
        - Seeds
      description: >
        Updates a seed group.
      x-mint:
        metadata:
          title: Update Seed Group
      security:
        - OAuth2:
            - assetdiscovery_ow
    delete:
      operationId: deleteSeedGroup
      tags:
        - Seeds
      description: >
        Deletes a seed group. All seeds in the seed group will be deleted, and
        any assets discovered from those seeds will be removed from the
        listing associated with the seed group that owns the deleted seed.
      x-mint:
        metadata:
          title: Delete Seed Group
      security:
        - OAuth2:
            - assetdiscovery_ow

  /v1/organizations/{organizationUid}/seed-groups/{seedGroupUid}/seeds:
    get:
      operationId: getSeeds
      tags:
        - Seeds
      description: >
        Retrieve and filter seeds for a seed group.
      x-mint:
        metadata:
          title: Get Seeds in a Seed Group
      security:
        - OAuth2:
            - assetdiscovery_or
            - assetdiscovery_gr
            - assetdiscovery_lr
    post:
      operationId: postSeed
      tags:
        - Seeds
      description: >
        Creates a new seed if valid.
      x-mint:
        metadata:
          title: Create Seed
      security:
        - OAuth2:
            - assetdiscovery_ow
            - asset_client_lw

  /v1/organizations/{organizationUid}/seed-groups/{seedGroupUid}/seeds/{seedUid}:
    get:
      operationId: getSeed
      tags:
        - Seeds
      description: >
        Retrieves a single seed.
      x-mint:
        metadata:
          title: Get Seed
      security:
        - OAuth2:
            - assetdiscovery_or
            - assetdiscovery_gr
            - assetdiscovery_lr
    delete:
      operationId: deleteSeed
      tags:
        - Seeds
      description: >
        Delete seeds. Any assets discovered from those seeds will be removed
        from the listing associated with the seed group that owns the deleted
        seed.
      x-mint:
        metadata:
          title: Delete Seed
      security:
        - OAuth2:
            - assetdiscovery_ow

  /v1/organizations/{organizationUid}/seed-groups/{seedGroupUid}/tags/batchUpdate:
    post:
      operationId: updateSeedGroupTags
      tags:
        - Seeds
        - Tags
      description: >
        Updates a seed groups tags.
      x-mint:
        metadata:
          title: Update Seed Group Tags
      security:
        - OAuth2:
            - assetdiscovery_ow

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "login.synack.com"
          scopes:
            assetdiscovery_gr: Grants global-level to read seed groups and seeds.
            assetdiscovery_or: Grants organization-level to read seed groups and seeds.
            assetdiscovery_ow: Grants organization-level to create or modify seed groups and seeds.
            assetdiscovery_lr: Grants listing-level to read seed groups and seeds.
            asset_client_lw: Grants listing-level to write seed groups and seeds.
