openapi: 3.0.3
info:
  title: Asset Service
  version: 2.1.020
  contact:
    name: Synack Engineering
    email: engineering@synack.com
tags:
  - name: asset-relationships
    description: Relationships between assets.
  - name: Assets
    description: Assets managed by Synack.
  - name: cloudaccounts
    description: Cloud account assets.
  - name: credentials
    description: Credentials are restricted to authorized users.
  - name: Hosts
    description: Host assets.
  - name: Assessments
    description: Assets are associated with listings.
  - name: mobileapps
    description: Mobile application assets.
  - name: networks
    description: Network assets.
  - name: ports
    description: Ports for single host assets.
  - name: scoperules
    description: Scope-rules provide fine grained control for what is in and out of scope for an asset.
  - name: scripts
    description: Scripts for mobile and web applications.
  - name: userroles
    description: Defines persona-specific user roles for asset credential management.
  - name: users
    description: Users of credentials.
  - name: webapps
    description: Web application assets.
servers:
  - url: https://client.synack.com/api/asset
    description: Commercial 
  - url: https://client.synack.us/api/asset
    description: FedRAMP (Medium)
paths:
  /v2/bulk/assets:
    post:
      operationId: postAssetBulk
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Bulk upserts array of assets and listing associations. Checks properties
        of assets for validity and returns 409 Conflict if rules are violated.
        Relationships can be upserted using the sourceRelationships property only.
      x-mint:
        metadata:
          title: Bulk Create Assets
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/bulk/assets/lifecycle-state:update:
    post:
      operationId: bulkUpdateAssetLifecycleState
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Bulk updates the asset life cycle property. Checks the validity of assets and returns 409 Conflict if rules are violated.
      x-mint:
        metadata:
          title: Bulk Update Asset Lifecycle State 
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/bulk/assets/criticality:update:
    post:
      operationId: bulkUpdateAssetCriticality
      tags:
        - Assets
        - cloudaccounts
        - hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Bulk update the criticality of multiple assets.
      x-mint:
        metadata:
          title: Bulk Update Asset Criticality
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/listings/{listingUid}/assets/{assetUid}:
    put:
      operationId: putListingAsset
      tags:
        - Assessments
      description: Upsert assignment of an asset to a listing.
      x-mint:
        metadata:
          title: Add Asset to Assessment 
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_client_lw
            - asset_boss_ow
            - asset_boss_lw
    delete:
      operationId: deleteListingAsset
      tags:
        - Assessments
      description: Delete the assignment of an asset to a listing.
      x-mint:
        metadata:
          title: Remove Asset from Assessment 
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/listings/{listingUid}/assets:
    patch:
      operationId: patchListingAssets
      tags:
        - Assessments
      description: Associate or disassociate zero or more assets from a listing.
        Allows the caller to provide lists of assets to add to and/or remove from
        being associated with a listing. Unknown assets are ignored.
      x-mint:
        metadata:
          title: Add or Remove Multiple Assets to/from Asessment
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_client_lw
            - asset_boss_ow
            - asset_boss_lw
    delete:
      operationId: deleteListingAssets
      tags:
        - Assessments
      description: Delete all the association of assets from a listing.
      x-mint:
        metadata:
          title: Remove All Assets from Assessment
      security:
        - OAuth2:
            - asset_gw
            - asset_boss_ow
            - asset_boss_lw
            - asset_client_ow
            - asset_client_lw

  /v2/organizations/{organizationUid}/listings/{listingUid}/gateways:
    patch:
      x-excluded: true
      operationId: patchListingGateways
      tags:
        - Assessments
      description: |
        Associate or disassociate gateway ID from a listing.
        Allows the caller to provide gateway ID to add to and/or remove from
        being associated with a listing. Gateway ID equals to `"nil"` would disassociate.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_client_lw
            - asset_boss_ow
            - asset_boss_lw

  /v2/listings/{listingUid}/reset-scope-rules:
    put:
      x-excluded: true
      operationId: putListingAssetsResetScopeRules
      tags:
        - Assessments
      description: For every asset associated with the listing, reset the scope rules to default rules
      security:
        - OAuth2:
            - asset_gw
            - asset_boss_ow
            - asset_boss_lw

  /v2/assets:
    get:
      operationId: getAssets
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Retrieve the list of assets for one or more organizations, considering
        filtering and pagination query parameters. When an organization-level
        OAuth2 scope is provided, the results will be restricted to those
        organizations the user is authorized for. Similarly, if a listing-
        level OAuth2 scope is provided, the results will be restricted to those
        listings the user is authorized for.

        Additional query parameters generally restrict the resulting set of
        assets according to AND semantics.

        Use of organizationUid and listingUid query parameters will further
        restrict the results.

        If neither are specified, the returned assets are the set of assets
        the user is allowed to access with organization OR listing specific
        privileges.

        If listing UIDs are supplied without organization UIDs, then only the
        assets assigned to those listings (which the user is authorized for)
        will be returned. Conversely, if organization UIDs are supplied without
        listing UIDs, then only the assets owned by those organizations (which
        the the user is authorized for) will be returned.

        Should both organization UIDs and listing UIDs be supplied, then the set
        of assets returned is restricted to assets assigned to any of the
        supplied listings, AND owned by any of the supplied organizations,
        further restricted to only those the user is authorized to access.

        Researcher users are restricted to only viewing credentials of in scope
        assets for listings to which they have been assigned.
      x-mint:
        metadata:
          title: Get Assets
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
            - asset_scan_gr
    post:
      operationId: postAsset
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Creates an asset in my Synack org.
      x-mint:
        metadata:
          title: Create Asset
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
  /v2/assets/{assetUid}/whois:
    get:
      operationId: getWHOIS
      tags:
        - Assets
        - Hosts
      description: >
        Retrieves the WHOIS data for a single asset.
      x-mint:
        metadata:
          title: Get WHOIS for Asset
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
            - asset_scan_gr
    put:
      x-excluded: true
      operationId: putWHOIS
      tags:
        - Assets
        - Hosts
      description: >
        Adds the WHOIS data to a single asset.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
  /v2/assets/{assetUid}:
    get:
      operationId: getAsset
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Retrieves a single asset. If the user is a researcher, only the credentials they are authorized to access will be returned.
        If the asset is of cloud account type, only a user with asset_scan_gr scope can access its credential data.
      x-mint:
        metadata:
          title: Get Asset
      security:
        - OAuth2:
            - asset_gr
            - asset_scan_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
    patch:
      operationId: patchAsset
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Patches the properties of a single asset.
      x-mint:
        metadata:
          title: Patch Asset
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteAsset
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Deletes an asset. This is intended to be a privileged operation.
        Regular use should be to mark the asset as inactive. Any relationships
        that involve the deleted asset will be also be deleted, as will any
        association to listings.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/assets/{assetUid}/related-assets:
    get:
      operationId: getRelatedAssets
      tags:
        - Assets
      description: >
        Returns all assets that share a relationship with the matched Asset UID.
      x-mint:
        metadata:
          title: Get Related Assets
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
            - asset_scan_gr

  /v2/assets/{assetUid}/tools/burp/target-scope.json:
    get:
      x-excluded: true
      operationId: getBurpTargetScopeForAsset
      tags:
        - Assets
        - webapps
      description: >
        Retrieve a Burp target scope file, if the asset is a webapp.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr

  /v2/assets/{assetUid}/scripts:
    get:
      x-excluded: true
      operationId: getAssetScripts
      tags:
        - webapps
        - mobileapps
        - scripts
      description:
        Gets all scripts owned by the mobile or web application asset. Returns 409 status
        if the asset is not of one of these types.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
    post:
      x-excluded: true
      operationId: postAssetScript
      tags:
        - webapps
        - mobileapps
        - scripts
      description: >
        Adds a script to a mobile or web application asset. Returns 409 status if the asset
        is of any other type..
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/assets/{assetUid}/credentials:
    get:
      x-excluded: true
      operationId: getAssetCredentials
      tags:
        - webapps
        - mobileapps
        - credentials
      description:
        Gets all credentials owned by web application asset. Returns 409 status
        if the asset is not of this type.
      security:
        - OAuth2:
            - asset_gr
            - asset_scan_gr
            - asset_or

  /v2/scripts/{scriptUid}:
    get:
      x-excluded: true
      operationId: getAssetScript
      tags:
        - mobileapps
        - scripts
        - webapps
      description: Gets an asset script.
      security:
        - OAuth2:
            - asset_gr
            - asset_scan_gr
            - asset_or
            - asset_lr
    delete:
      x-excluded: true
      operationId: deleteAssetScript
      tags:
        - mobileapps
        - scripts
        - webapps
      description: >
        Delete a script from a asset.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    patch:
      x-excluded: true
      operationId: patchAssetScript
      tags:
        - mobileapps
        - scripts
        - webapps
      description: >
        Patch the properties of an asset script.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/scripts/{scriptUid}/script-data:
    get:
      x-excluded: true
      operationId: getAssetScriptData
      tags:
        - mobileapps
        - scripts
        - webapps
      description: Gets the script data for an asset script.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr

  /v2/assets/{assetUid}/ports/{portNumber}/{portProtocol}:
    get:
      operationId: getHostPort
      tags:
        - Hosts
        - ports
      description: >
        Retrieve a port for a host asset.
      x-mint:
        metadata:
          title: Get Port for Host Asset 
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
    put:
      x-excluded: true
      operationId: putHostPort
      tags:
        - Hosts
        - ports
      description: >
        Upsert a port to a host asset. Will return 409 status if the asset
        is not a single host (i.e. a CIDR).
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    patch:
      x-excluded: true
      operationId: patchHostPort
      tags:
        - Hosts
        - ports
      description: >
        Update properties of a port belonging a single-IP host asset.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteHostPort
      tags:
        - Hosts
        - ports
      description: >
        Delete a port from a host asset. Will return 409 status if the asset
        is not a single host (i.e. a CIDR).
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/assets/{assetUid}/binaries/{version}:
    put:
      x-excluded: true
      operationId: putApplicationBinary
      tags:
        - mobileapps
      description: >
        Upsert an application binary file or the Url to the binary in the app store.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteApplicationBinary
      tags:
        - mobileapps
      description: >
        Delete an application binary.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/assets/{assetUid}/user-roles:
    get:
      x-excluded: true
      operationId: getUserRoles
      tags:
        - mobileapps
        - webapps
        - userroles
      description: Gets a paginated list of all user roles for a mobile or
        web application. Returns a 409 status code if the asset is
        not one of these expected types.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
    post:
      x-excluded: true
      operationId: postUserRole
      tags:
        - mobileapps
        - webapps
        - userroles
      description:
        Adds a user role to a mobile or web application asset. Returns
        a 409 status code if the asset is not one of these expected types.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/user-roles/{userRoleUid}:
    get:
      x-excluded: true
      operationId: getUserRole
      tags:
        - mobileapps
        - webapps
        - userroles
      description: Retrieves the properties of the supplied user role.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
    patch:
      x-excluded: true
      operationId: patchUserRole
      tags:
        - mobileapps
        - webapps
        - userroles
      description:
        Patch properties of a user role for a mobile or web application asset.
        Will return a 409 status code if the type is not one of these expected
        types.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteUserRole
      tags:
        - mobileapps
        - webapps
        - userroles
      description:
        Delete a user role from a mobile or web application asset. Will
        return a 409 status code if the type is not one of these expected
        types.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/user-roles/{userRoleUid}/scripts/{scriptUid}:
    patch:
      x-excluded: true
      operationId: patchUserRoleScript
      tags:
        - mobileapps
        - webapps
        - userroles
        - scripts
      description: Patch properties of a script that's been assigned to user role for a mobile or web application asset.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/assets/{assetUid}/scope-rules:
    get:
      x-excluded: true
      operationId: getScopeRules
      tags:
        - Hosts
        - webapps
        - scoperules
      description: Gets a list of all scope rules for a host or web application asset.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_srt_lr
    post:
      x-excluded: true
      operationId: postScopeRule
      tags:
        - Hosts
        - webapps
        - scoperules
      description: Adds a scope rule to a web application or host asset.
        Returns a 409 status code if the asset is not one of these expected types.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/scope-rules/{scopeRuleUid}:
    get:
      x-excluded: true
      operationId: getScopeRule
      tags:
        - Hosts
        - webapps
        - scoperules
      description: Retrieve a scope rule.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
    patch:
      x-excluded: true
      operationId: patchScopeRule
      tags:
        - Hosts
        - webapps
        - scoperules
      description:
        Patch properties of a scope rule for a host asset with CIDRs or web application asset.
        Will return a 409 status code if the type is not one of these expected types.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteScopeRule
      tags:
        - Hosts
        - webapps
        - scoperules
      description:
        Delete a scope rule from a host or web application asset. Will
        return a 409 status code if the type is not one of these expected
        types.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/user-roles/{userRoleUid}/user-role-credentials:
    get:
      x-excluded: true
      operationId: getUserRoleCredentials
      tags:
        - mobileapps
        - webapps
        - credentials
        - userroles
      description: Gets the paginated credentials owned by the user role.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
    post:
      x-excluded: true
      operationId: postUserRoleCredential
      tags:
        - mobileapps
        - webapps
        - credentials
        - userroles
      description:
        Add a credential to a user role. Returns 409 Conflict if the credentials
        do not match the structure of previously created credentials.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    patch:
      x-excluded: true
      operationId: patchUserRoleCredentials
      tags:
        - mobileapps
        - webapps
        - credentials
        - userroles
      description:
        Update the properties of multlipe user role credentials. Returns 409
        Conflict when the credential format does not match existing
        credentials.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

    delete:
      x-excluded: true
      operationId: deleteUserRoleCredentials
      tags:
        - mobileapps
        - webapps
        - credentials
        - userroles
      description: Delete every credential belonging to the user role.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/user-role-credentials/{credentialUid}:
    delete:
      x-excluded: true
      operationId: deleteUserRoleCredential
      tags:
        - mobileapps
        - webapps
        - credentials
        - userroles
      description: Delete a user role credentialt.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    patch:
      x-excluded: true
      operationId: patchUserRoleCredential
      tags:
        - credentials
        - mobileapps
        - webapps
        - userroles
      description:
        Patch the properties of a user-role credential. Returns 409 Conflict if the credentials
        do not match the structure of previously created credentials.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/user-role-credentials/{credentialUid}/assigned-users/{userUid}:
    put:
      x-excluded: true
      operationId: putUserRoleCredentialUser
      tags:
        - credentials
        - mobileapps
        - webapps
        - userroles
        - users
      description:
        Assign a user to a user-role credential. Credentials with sharing of
        "one" will return a 409 status code when a request is received to add
        further users. Credentials with sharing of "all" will return a 409
        status code on any request to add users. There is not limit to the
        number of users that may be added for sharing of "many".
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteUserRoleCredentialUser
      tags:
        - credentials
        - mobileapps
        - webapps
        - userroles
        - users
      description: Remove a user from a user-role credential.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/user-role-credentials:
    post:
      x-excluded: true
      operationId: assignUserRoleCredentialsToUser
      tags:
        - mobileapps
        - webapps
        - credentials
        - userroles
        - users
      description:
        Assign user role credentials to a user for mobile application or
        web application assets in a listing.
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr

  /v2/asset-relationships:
    post:
      x-excluded: true
      operationId: postAssetRelationship
      tags:
        - asset-relationships
      description: >
        Creates a relationship between two assets.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/asset-relationships/{assetRelationshipUid}:
    patch:
      x-excluded: true
      operationId: patchAssetRelationship
      tags:
        - asset-relationships
      description: >
        Updates a relationship between a two assets.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteAssetRelationship
      tags:
        - asset-relationships
      description: >
        Deletes a relationship between a two assets.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/external-relationships:
    post:
      x-excluded: true
      operationId: postExternalRelationship
      tags:
        - external-relationships
      description: Creates a relationship between asset in AssetService and an
        external service.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/external-relationships/{assetRelationshipUid}:
    patch:
      x-excluded: true
      operationId: patchExternalRelationship
      tags:
        - external-relationships
      description: Updates a relationship between a two assets.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw
    delete:
      x-excluded: true
      operationId: deleteExternalRelationship
      tags:
        - external-relationships
      description: Deletes a relationship between a two assets.
      security:
        - OAuth2:
            - asset_gw
            - asset_client_ow
            - asset_boss_ow
            - asset_client_lw
            - asset_boss_lw

  /v2/asset-stats:
    get:
      operationId: getAssetStats
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - webapps
      description: >
        Returns active assets under test (in scope for a listing) and total active assets for the supplied organization and listings.
      x-mint:
        metadata:
          title: Get Asset Stats 
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr

  /v2/organizations/{organizationUid}/discovered-assets:
    get:
      operationId: getDiscoveredAssetSummaries
      tags:
        - Assets
        - cloudaccounts
        - Hosts
        - mobileapps
        - networks
        - webapps
      description: >
        Retrieve the list summarized properties for discovered assets belonging
        to  an organization, considering filtering and pagination query
        parameters.

        Additional query parameters generally restrict the resulting set of
        assets according to AND semantics.
      x-mint:
        metadata:
          title: Get Discovered Assets 
      security:
        - OAuth2:
            - asset_gr
            - asset_or
            - asset_lr
            - asset_srt_lr
            - asset_scan_gr

  /v2/listing-webapps/{listingUid}:
    get:
      x-excluded: true
      operationId: getWebApps
      tags:
        - webapps
      description:
        Gets a list of active webapps with all their HTTPing settings,
        scope rules, session handling scripts, SRT credentials and credential user
        UIDs for the given listing. Used to generate input for TarantulaBurp and
        TarantulaBurpValidator plugins.
      security:
        - OAuth2:
            - asset_gr
            - asset_scan_gr
            - asset_lr

  /v2/webapps/{assetUid}:
    get:
      x-excluded: true
      operationId: getWebApp
      tags:
        - webapps
      description:
        Gets a webapp with all assigned HTTPing settings, scope rules,
        session handling scripts, SRT credentials and credential user UIDs.
        Used to generate input for TarantulaBurp and TarantulaBurpValidator plugins.
      security:
        - OAuth2:
            - asset_gr
            - asset_scan_gr

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "login.synack.com"
          scopes:
            #TODO review these scopes; especially if the asset service is no longer listing aware
            asset_lr: Grants per-listing read access for all types of assets.
            asset_srt_lr: Grants per-listing read access to assets that may be read by SRTs.
            asset_or: Grants organization-level read access for all types of assets owned by a particular organization.
            asset_boss_ow: Grants organization-level access to assets owned by a particular organization that may be modified by BOSS users.
            asset_boss_lw: Grants per-listing write access to assets that may be modified by BOSS users.
            asset_client_ow: Grants organization-level access to assets owned by a particular organization that may be modified by Client users.
            asset_client_lw: Grants per-listing write access to assets that may be modified by Client users.
            asset_user_or: Grants user-level read access to asset stats that owned by a particular organization.
            asset_gr: Grants unrestricted read access to all assets. Except for credential data of cloud accout assets.
            asset_gw: Grants unrestricted write access to all assets.
            asset_scan_gr: Grants unrestricted read access to all assets. Including credential data of cloud account assets.
  # types reference for proper client code generation by oapi-codegen